### ISSUE TITLE
MemoryError when importing 484mb JSON File

### ISSUE THREAD

**Issue by ROODAY** [firebase/firebase-streaming-import#5]
When running

`python import.py https://necir-hackathon.firebaseio.com/ test.json`

I get this stacktrace:

```
started at 1469480152.98
Traceback (most recent call last):
  File "import.py", line 90, in <module>
    main(argParser.parse_args())
  File "import.py", line 20, in main
    for prefix, event, value in parser:
  File "R:\Python27\lib\site-packages\ijson\common.py", line 65, in parse
    for event, value in basic_events:
  File "R:\Python27\lib\site-packages\ijson\backends\python.py", line 185, in basic_parse
    for value in parse_value(lexer):
  File "R:\Python27\lib\site-packages\ijson\backends\python.py", line 116, in parse_value
    for event in parse_array(lexer):
  File "R:\Python27\lib\site-packages\ijson\backends\python.py", line 138, in parse_array
    for event in parse_value(lexer, symbol, pos):
  File "R:\Python27\lib\site-packages\ijson\backends\python.py", line 119, in parse_value
    for event in parse_object(lexer):
  File "R:\Python27\lib\site-packages\ijson\backends\python.py", line 160, in parse_object
    pos, symbol = next(lexer)
  File "R:\Python27\lib\site-packages\ijson\backends\python.py", line 59, in Lexer
    buf += data
MemoryError
```

Test.json is 484 mb, but shouldn't that not be a problem?

**Comment by JMatharu** [comment]
![04_37_48-administrator_ c__windows_system32_cmd exe-mathaj-000450](https://cloud.githubusercontent.com/assets/5781893/17495773/5af2029c-5d88-11e6-912b-a44bbf57d580.png)

Same issue with me and the file size is 135MB

**Comment by ROODAY** [comment]
I'm not sure, but I think this error is due to a particular object/property
being too large. I don't how to get the Streaming Import tool to work, but
writing a custom script in Node.js ended up being far more efficient.
Here's the code I used, you can modify it to fit your needs:
https://raw.githubusercontent.com/ROODAY/NECIR-Hackathon/conversion-script/uploader.js

It converts CSV to JSON before uploading, but you could just make use of
the uploading bit if you already have JSON. Just note that in its current
state, it notifies when the last object has been uploaded to Firebase, but
the script will still need to run for a while if you are uploading a lot of
data, as it seemed that Firebase needs some more time to save the data it
receives.

**Comment by lowe0292** [comment]
Might be unrelated, but I think there's a memory leak. I'm running the import script against ~400MB json file and it's taking on the order of 10GB of RAM to complete.

**Comment by lowe0292** [comment]
Alright think I figured it out. Apparently the pp module that this is using to do the requests in parallel won't release the memory until you read the result, and reading the result significantly slows down the process.

I replaced [this line](https://github.com/firebase/firebase-streaming-import/blob/master/import.py#L17) with `parallelJobs = pp.Server('autodetect', (), None, True)`, and it seemed to do the trick (the fourth param is whether to restart worker process after each task completion and defaults to false).

**Comment by lowe0292** [comment]
Scratch that, still leaking.

Reading the result appears to resolve the memory issue, but it slows the individuals requests by a ton. I'll leave it running overnight and see where it's at in the AM.

**Comment by philshem** [comment]
@lowe0292 is it still running?  ;)

**What's the status of this repository?** 
I see no updates for 4 years, and my uploads never finish.

**Comment by lowe0292** [comment]
@philshem never solved it and gave up, Sorry!

**Comment by ROODAY** [comment]
@philshem Did you try the [uploader script](https://github.com/ROODAY/NECIR-Hackathon/blob/conversion-script/uploader.js) I made? I haven't touched it since I made it but it worked at the time, might help ya here.

**Comment by philshem** [comment]
@ROODAY I saw it but didn't use it because simpler than editing the script was for me to splitting my BIG json in 10 smaller ones, and looping around [firebase-import](https://github.com/firebase/firebase-import).

**Comment by ROODAY** [comment]
Closing as there are posted workarounds above, feel free to re-open if the bug is being worked on!
